import type { Booking, Event, EventCategory, Review, User } from "./types";

export const mockUsers: User[] = [
  {
    id: "user_1",
    email: "john@example.com",
    fullName: "John Anderson",
    role: "user",
    avatar: "/professional-man-headshot.png",
    bio: "Adventure seeker and music enthusiast. Always looking for new experiences!",
    interests: ["Music", "Hiking", "Photography", "Travel"],
    location: "San Francisco, CA",
    createdAt: "2024-01-15T10:00:00Z",
    rating: 4.8,
    reviewCount: 12,
  },
  {
    id: "user_2",
    email: "sarah@example.com",
    fullName: "Sarah Mitchell",
    role: "host",
    avatar: "/professional-woman-headshot.png",
    bio: "Event organizer passionate about bringing people together. Specializing in outdoor adventures and cultural experiences.",
    interests: ["Events", "Outdoor", "Culture", "Networking"],
    location: "Los Angeles, CA",
    createdAt: "2023-08-20T10:00:00Z",
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: "user_3",
    email: "mike@example.com",
    fullName: "Mike Chen",
    role: "host",
    avatar: "/asian-man-professional-headshot.png",
    bio: "Tech meetup organizer and board game enthusiast. Building community through shared interests.",
    interests: ["Technology", "Gaming", "Startups", "Coffee"],
    location: "Seattle, WA",
    createdAt: "2023-11-05T10:00:00Z",
    rating: 4.7,
    reviewCount: 28,
  },
  {
    id: "user_4",
    email: "emma@example.com",
    fullName: "Emma Wilson",
    role: "user",
    avatar: "/young-woman-smiling-headshot.png",
    bio: "Yoga instructor and wellness advocate. Love connecting with mindful individuals.",
    interests: ["Yoga", "Wellness", "Meditation", "Healthy Living"],
    location: "Austin, TX",
    createdAt: "2024-02-10T10:00:00Z",
    rating: 4.6,
    reviewCount: 8,
  },
  {
    id: "admin_1",
    email: "admin@eventhub.com",
    fullName: "Admin User",
    role: "admin",
    avatar: "/administrator-avatar.jpg",
    bio: "Platform administrator",
    interests: [],
    location: "Remote",
    createdAt: "2023-01-01T10:00:00Z",
    rating: 5,
    reviewCount: 0,
  },
];

export const mockEvents: Event[] = [
  {
    id: "event_1",
    name: "Sunset Hiking Adventure",
    description:
      "Join us for a breathtaking sunset hike through the coastal trails. Perfect for beginners and experienced hikers alike. We'll capture amazing photos and enjoy the beautiful California coastline.",
    category: "hiking",
    date: "2025-01-15",
    time: "16:00",
    location: "Marin Headlands",
    address: "948 Fort Barry, Sausalito, CA 94965",
    image: "/sunset-hiking-trail-mountains.jpg",
    hostId: "user_2",
    host: mockUsers[1],
    minParticipants: 4,
    maxParticipants: 12,
    currentParticipants: 8,
    participants: [mockUsers[0], mockUsers[3]],
    fee: 15,
    status: "open",
    createdAt: "2024-12-01T10:00:00Z",
  },
  {
    id: "event_2",
    name: "Board Game Night",
    description:
      "Weekly board game night at the local cafe. Bring your favorite games or try out our collection. Great way to meet new people and have fun!",
    category: "gaming",
    date: "2025-01-10",
    time: "19:00",
    location: "GameHaus Cafe",
    address: "1800 S Brand Blvd, Glendale, CA 91204",
    image: "/board-games-night-friends-playing.jpg",
    hostId: "user_3",
    host: mockUsers[2],
    minParticipants: 6,
    maxParticipants: 20,
    currentParticipants: 14,
    participants: [mockUsers[0]],
    fee: 0,
    status: "open",
    createdAt: "2024-12-05T10:00:00Z",
  },
  {
    id: "event_3",
    name: "Jazz Night at Blue Note",
    description:
      "Experience live jazz at one of the most iconic jazz clubs. Featuring local artists and a welcoming atmosphere for jazz lovers of all backgrounds.",
    category: "music",
    date: "2025-01-20",
    time: "20:00",
    location: "Blue Note Jazz Club",
    address: "131 W 3rd St, New York, NY 10012",
    image: "/jazz-club-live-music-performance.jpg",
    hostId: "user_2",
    host: mockUsers[1],
    minParticipants: 8,
    maxParticipants: 25,
    currentParticipants: 18,
    participants: [mockUsers[3]],
    fee: 35,
    status: "open",
    createdAt: "2024-12-08T10:00:00Z",
  },
  {
    id: "event_4",
    name: "Tech Startup Networking",
    description:
      "Connect with fellow entrepreneurs, developers, and tech enthusiasts. Share ideas, find collaborators, and grow your network in the tech industry.",
    category: "tech",
    date: "2025-01-25",
    time: "18:00",
    location: "WeWork Downtown",
    address: "600 California St, San Francisco, CA 94108",
    image: "/tech-networking-event-startup-meetup.jpg",
    hostId: "user_3",
    host: mockUsers[2],
    minParticipants: 15,
    maxParticipants: 50,
    currentParticipants: 32,
    participants: [mockUsers[0]],
    fee: 10,
    status: "open",
    createdAt: "2024-12-10T10:00:00Z",
  },
  {
    id: "event_5",
    name: "Morning Yoga in the Park",
    description:
      "Start your day with energizing yoga sessions in the beautiful park setting. All levels welcome. Bring your own mat or borrow one of ours.",
    category: "wellness",
    date: "2025-01-12",
    time: "07:00",
    location: "Golden Gate Park",
    address: "Music Concourse Dr, San Francisco, CA 94122",
    image: "/outdoor-yoga-park-morning-sunrise.jpg",
    hostId: "user_2",
    host: mockUsers[1],
    minParticipants: 5,
    maxParticipants: 30,
    currentParticipants: 22,
    participants: [mockUsers[3]],
    fee: 12,
    status: "open",
    createdAt: "2024-12-12T10:00:00Z",
  },
  {
    id: "event_6",
    name: "Food Tour: Little Italy",
    description:
      "Discover the best authentic Italian restaurants, bakeries, and cafes. Sample delicious food while learning about the neighborhood's rich history.",
    category: "food",
    date: "2025-01-18",
    time: "11:00",
    location: "Little Italy",
    address: "Mulberry St, New York, NY 10013",
    image: "/italian-food-tour-restaurant-pasta.jpg",
    hostId: "user_2",
    host: mockUsers[1],
    minParticipants: 6,
    maxParticipants: 15,
    currentParticipants: 12,
    participants: [mockUsers[0], mockUsers[3]],
    fee: 45,
    status: "open",
    createdAt: "2024-12-15T10:00:00Z",
  },
  {
    id: "event_7",
    name: "Art Gallery Opening",
    description:
      "Be part of an exclusive gallery opening featuring emerging contemporary artists. Enjoy wine, appetizers, and meaningful conversations about art.",
    category: "art",
    date: "2025-02-01",
    time: "19:00",
    location: "Modern Art Gallery",
    address: "450 Broadway, Los Angeles, CA 90013",
    image: "/art-gallery-opening-modern-exhibition.jpg",
    hostId: "user_2",
    host: mockUsers[1],
    minParticipants: 10,
    maxParticipants: 40,
    currentParticipants: 28,
    participants: [],
    fee: 25,
    status: "open",
    createdAt: "2024-12-18T10:00:00Z",
  },
  {
    id: "event_8",
    title: "Basketball Pickup Game",
    description:
      "Weekly basketball pickup games for all skill levels. Come for the exercise, stay for the community. Beginners and experienced players welcome!",
    category: "sports",
    date: "2025-01-14",
    time: "10:00",
    location: "Venice Beach Courts",
    address: "1800 Ocean Front Walk, Venice, CA 90291",
    image: "/basketball-outdoor-court-game.jpg",
    hostId: "user_3",
    host: mockUsers[2],
    minParticipants: 10,
    maxParticipants: 20,
    currentParticipants: 16,
    participants: [mockUsers[0]],
    fee: 0,
    status: "OPEN",
    createdAt: "2024-12-20T10:00:00Z",
  },
];

export const mockReviews: Review[] = [
  {
    id: "review_1",
    eventId: "event_1",
    userId: "user_1",
    user: mockUsers[0],
    hostId: "user_2",
    rating: 5,
    comment:
      "Amazing experience! Sarah is an incredible host who made everyone feel welcome. The sunset views were breathtaking.",
    createdAt: "2024-11-20T10:00:00Z",
  },
  {
    id: "review_2",
    eventId: "event_2",
    userId: "user_4",
    user: mockUsers[3],
    hostId: "user_3",
    rating: 4,
    comment:
      "Great selection of games and friendly atmosphere. Mike knows how to keep everyone engaged. Will definitely come back!",
    createdAt: "2024-11-25T10:00:00Z",
  },
  {
    id: "review_3",
    eventId: "event_3",
    userId: "user_1",
    user: mockUsers[0],
    hostId: "user_2",
    rating: 5,
    comment:
      "The jazz night was phenomenal. Sarah picked the perfect venue and the live music was incredible. Highly recommend!",
    createdAt: "2024-12-01T10:00:00Z",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "booking_1",
    eventId: "event_1",
    event: mockEvents[0],
    userId: "user_1",
    user: mockUsers[0],
    status: "confirmed",
    paidAmount: 15,
    bookedAt: "2024-12-05T10:00:00Z",
  },
  {
    id: "booking_2",
    eventId: "event_3",
    event: mockEvents[2],
    userId: "user_4",
    user: mockUsers[3],
    status: "confirmed",
    paidAmount: 35,
    bookedAt: "2024-12-10T10:00:00Z",
  },
];

export const eventCategories: {
  value: EventCategory;
  label: string;
  icon: string;
}[] = [
  { value: "concert", label: "Concerts", icon: "Music" },
  { value: "sports", label: "Sports", icon: "Trophy" },
  { value: "hiking", label: "Hiking", icon: "Mountain" },
  { value: "gaming", label: "Gaming", icon: "Gamepad2" },
  { value: "food", label: "Food & Dining", icon: "UtensilsCrossed" },
  { value: "art", label: "Art & Culture", icon: "Palette" },
  { value: "tech", label: "Tech & Startup", icon: "Laptop" },
  { value: "music", label: "Music", icon: "Headphones" },
  { value: "wellness", label: "Wellness", icon: "Heart" },
  { value: "social", label: "Social", icon: "Users" },
];

export const interestOptions = [
  "Music",
  "Sports",
  "Hiking",
  "Photography",
  "Painting",
  "Cycling",
  "Programming",
  "Travel",
  "Gaming",
  "Technology",
  "Art",
  "Food",
  "Wellness",
  "Yoga",
  "Reading",
  "Movies",
  "Dancing",
  "Cooking",
  "Fitness",
  "Nature",
  "Networking",
  "Meditation",
  "Coffee",
  "Theater",
  "Comedy",
  "Volunteering",
];
