import type { Booking, Event, EventCategory, Review, User } from "./types";

export const mockUsers: User[] = [
  {
    id: "user_1",
    email: "alex@example.com",
    fullName: "Alex Parker",
    role: "user",
    avatar: "/avatars/man1.png",
    bio: "Explorer and foodie. Love discovering new adventures and cultures.",
    interests: ["Travel", "Food", "Photography", "Hiking"],
    location: "San Diego, CA",
    createdAt: "2024-02-10T10:00:00Z",
    rating: 4.7,
    reviewCount: 15,
  },
  {
    id: "user_2",
    email: "olivia@example.com",
    fullName: "Olivia Brown",
    role: "host",
    avatar: "/avatars/woman1.png",
    bio: "Event curator specializing in cultural experiences and wellness retreats.",
    interests: ["Wellness", "Yoga", "Culture", "Networking"],
    location: "Los Angeles, CA",
    createdAt: "2023-09-12T10:00:00Z",
    rating: 4.9,
    reviewCount: 50,
  },
  {
    id: "user_3",
    email: "liam@example.com",
    fullName: "Liam Zhang",
    role: "host",
    avatar: "/avatars/man2.png",
    bio: "Tech community builder and board game enthusiast.",
    interests: ["Technology", "Gaming", "Startups", "Coffee"],
    location: "Seattle, WA",
    createdAt: "2023-11-15T10:00:00Z",
    rating: 4.8,
    reviewCount: 30,
  },
  {
    id: "user_4",
    email: "mia@example.com",
    fullName: "Mia Thompson",
    role: "user",
    avatar: "/avatars/woman2.png",
    bio: "Yoga instructor and wellness coach. Passionate about mindfulness and healthy living.",
    interests: ["Yoga", "Wellness", "Meditation", "Healthy Living"],
    location: "Austin, TX",
    createdAt: "2024-03-05T10:00:00Z",
    rating: 4.6,
    reviewCount: 10,
  },
  {
    id: "admin_1",
    email: "admin@evently.com",
    fullName: "Admin User",
    role: "admin",
    avatar: "/avatars/admin.png",
    bio: "Platform administrator",
    interests: [],
    location: "Remote",
    createdAt: "2023-01-01T10:00:00Z",
    rating: 5,
    reviewCount: 0,
  },
];

export const mockEvents: Event[] = [
  {
    id: "event_1",
    name: "Coastal Sunset Hike",
    description:
      "Enjoy an evening hike along the coast with breathtaking sunset views. Perfect for nature lovers and photographers.",
    category: "hiking",
    date: "2025-01-16",
    time: "17:00",
    location: "Point Reyes National Seashore",
    address: "1 Bear Valley Rd, Point Reyes Station, CA 94956",
    image: "/images/hiking-sunset.jpg",
    hostId: "user_2",
    host: mockUsers[1],
    minParticipants: 4,
    maxParticipants: 15,
    currentParticipants: 9,
    participants: [mockUsers[0], mockUsers[3]],
    fee: 20,
    status: "open",
    createdAt: "2024-12-01T10:00:00Z",
  },
  {
    id: "event_2",
    name: "Board Game Social",
    description:
      "Casual board game night at a cozy cafe. Bring your favorite game or try ours. Fun for beginners and pros!",
    category: "gaming",
    date: "2025-01-11",
    time: "18:30",
    location: "GameSpace Cafe",
    address: "123 Main St, Seattle, WA 98101",
    image: "/images/board-game-night.jpg",
    hostId: "user_3",
    host: mockUsers[2],
    minParticipants: 6,
    maxParticipants: 18,
    currentParticipants: 12,
    participants: [mockUsers[0]],
    fee: 0,
    status: "open",
    createdAt: "2024-12-05T10:00:00Z",
  },
  {
    id: "event_3",
    name: "Jazz Evening at Blue Note",
    description:
      "Immerse yourself in live jazz performances at a renowned club. Enjoy music, drinks, and a vibrant atmosphere.",
    category: "music",
    date: "2025-01-21",
    time: "20:30",
    location: "Blue Note Jazz Club",
    address: "131 W 3rd St, New York, NY 10012",
    image: "/images/jazz-night.jpg",
    hostId: "user_2",
    host: mockUsers[1],
    minParticipants: 8,
    maxParticipants: 25,
    currentParticipants: 17,
    participants: [mockUsers[3]],
    fee: 40,
    status: "open",
    createdAt: "2024-12-08T10:00:00Z",
  },
];

export const mockReviews: Review[] = [
  {
    id: "review_1",
    eventId: "event_1",
    userId: "user_1",
    user: mockUsers[0],
    hostId: "user_2",
    rating: 5,
    comment:
      "Incredible sunset hike! Olivia guided us perfectly and the views were unforgettable.",
    createdAt: "2024-11-21T10:00:00Z",
  },
  {
    id: "review_2",
    eventId: "event_2",
    userId: "user_4",
    user: mockUsers[3],
    hostId: "user_3",
    rating: 4,
    comment:
      "Fun board game night! Liam made everyone feel included. Will definitely attend again.",
    createdAt: "2024-11-26T10:00:00Z",
  },
  {
    id: "review_3",
    eventId: "event_3",
    userId: "user_1",
    user: mockUsers[0],
    hostId: "user_2",
    rating: 5,
    comment:
      "The jazz evening was magical. Olivia created a perfect ambiance and the musicians were excellent.",
    createdAt: "2024-12-02T10:00:00Z",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "booking_1",
    eventId: "event_1",
    event: mockEvents[0],
    userId: "user_1",
    user: mockUsers[0],
    status: "confirmed",
    paidAmount: 20,
    bookedAt: "2024-12-06T10:00:00Z",
  },
  {
    id: "booking_2",
    eventId: "event_3",
    event: mockEvents[2],
    userId: "user_4",
    user: mockUsers[3],
    status: "confirmed",
    paidAmount: 40,
    bookedAt: "2024-12-11T10:00:00Z",
  },
];

export const eventCategories: {
  value: EventCategory;
  label: string;
  icon: string;
}[] = [
  { value: "concert", label: "Concerts", icon: "Music" },
  { value: "sports", label: "Sports", icon: "Trophy" },
  { value: "hiking", label: "Hiking", icon: "Mountain" },
  { value: "gaming", label: "Gaming", icon: "Gamepad2" },
  { value: "food", label: "Food & Dining", icon: "UtensilsCrossed" },
  { value: "art", label: "Art & Culture", icon: "Palette" },
  { value: "tech", label: "Tech & Startup", icon: "Laptop" },
  { value: "music", label: "Music", icon: "Headphones" },
  { value: "wellness", label: "Wellness", icon: "Heart" },
  { value: "social", label: "Social", icon: "Users" },
];

export const interestOptions = [
  "AI",
  "Blockchain",
  "Startups",
  "Public Speaking",
  "Event Management",
  "Marketing",
  "Design",
  "UX/UI",
  "Cyber Security",
  "Cloud Computing",
  "DevOps",
  "Machine Learning",
  "Data Science",
  "FinTech",
  "EdTech",
  "HealthTech",
  "Networking",
  "Leadership",
  "Product Management",
  "Innovation",
];
